# Configuration Nixpacks pour Coolify
# Utilise Node.js 20 avec npm (pas bun)

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
dependsOn = ["setup"]
nixPkgs = ["nodejs_20"]
nixLibs = ["stdenv"]

[start]
cmd = "npm run preview"

[variables]
NODE_ENV = "production"